# Generated by Django 4.2.5 on 2023-10-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('Joined', models.DateField(auto_now_add=True)),
                ('skills', models.CharField(choices=[('1', 'beginer'), ('2', 'Intermediate'), ('3', 'professional')], max_length=20, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('position', models.CharField(choices=[('bat', 'Batsman')], max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Info', to='detail.category')),
            ],
        ),
    ]
