# Generated by Django 4.2.5 on 2023-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='position',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='info',
            name='skills',
        ),
        migrations.AddField(
            model_name='info',
            name='levels',
            field=models.CharField(choices=[('1', 'zonal'), ('2', 'district'), ('3', 'state'), ('4', 'ranji'), ('5', 'Syed'), ('6', 'dilip'), ('7', 'Irani'), ('8', 'Deodar'), ('9', 'Vijay')], max_length=20, null=True),
        ),
    ]
