# Generated by Django 4.2.5 on 2023-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/pfp_images'),
        ),
    ]
