# Generated by Django 4.2.5 on 2023-10-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_alter_info_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Image',
            new_name='Profile_Image',
        ),
    ]
