# Generated by Django 4.2.5 on 2023-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_rename_image_info_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='skill',
            field=models.CharField(choices=[('bat', 'Batsman'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder')], max_length=30),
        ),
    ]
